# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bae61544707d3794bcc99a24da6b90a83e8d95b0d8fede0c3af93b121c0ea253ff676d7dba7b14b4815243a8fa2c2b5454196b5663d40a0588055252a32030ac

test:
  secret_key_base: 78db4fabda019d0d4093166644d25fcd994e8c68c618be34696dc2f5356131e09ecb0d980ba3475ddc599bbb8e24bf08610e27596f2c068fd34d796630548f3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
